# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:30"
    open-pull-requests-limit: 10

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:30"
    open-pull-requests-limit: 10
    groups:
      docker-actions:
        applies-to: version-updates
        patterns:
          - "docker/*"
      github-actions:
        applies-to: version-updates
        patterns:
          - "actions/*"
          - "github/*"
      lizardbyte-actions:
        applies-to: version-updates
        patterns:
          - "LizardByte/*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
    open-pull-requests-limit: 10
    groups:
      dev-dependencies:
        applies-to: version-updates
        dependency-type: "development"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:30"
    open-pull-requests-limit: 10

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00"
    open-pull-requests-limit: 10
    groups:
      pytest-dependencies:
        applies-to: version-updates
        patterns:
          - "pytest*"

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:30"
    open-pull-requests-limit: 10
